### ISSUE TITLE
decrypt without firefox extension

### ISSUE THREAD

**Issue by jozic** [diegocr/eComm#1]
Hi @diegocr 
how one would decrypt the text without a firefox/chrome extension?
Could you please provide an openssl command to decrypt text encrypted by your app?

Thank you.

**Comment by diegocr** [comment]
Hi @jozic

It should be possible indeed, but i'm not sure if openssl is enough.

Probably a tiny bash script using a few commands could do it, i can try to do some experiments once i have some spare time for this.

Cheers.

**Comment by jozic** [comment]
That would be great. 
Thanks!
